---
name: "research"
title: "research"
---


<style>
  .title{
    display: none;
  }
</style>

<link rel="stylesheet" href="styles.css" type="text/css">


#### [Two-party competition in the United States: Reversed growth trends](https://journals.sagepub.com/doi/full/10.1177/13540688221109780)


Does two-party competition in the United States lead to improved human welfare spending? The debate over the merits of competition has gained traction yet again in the study of American politics. Gerald Gamm and Thad Kousser suggest that from 1880 to 1980 two-party competition led to desirable outcomes like increased education, transportation, and health spending. The modern panel data presented here suggest the spending effects do not persist beyond 1980 up through 2020, and also, there is a negative effect on economic growth stemming from state-level partisan competition. The reversal of the historical trend is justified by predictions from existing formal models: at particularly high levels of baseline political competition, the effect of additional competition on growth is ambiguous.


#### [The Economic Background of City Councilmembers DRAFT](https://www.dropbox.com/scl/fi/rbrfq80xp1iwhip9e8yo2/councils_020924.pdf?rlkey=j8fnn23ccgu7vlryjtf2sls6i&dl=0)

How do the occupational backgrounds of city councilmembers shape local politics? An
older literature posits that local politics is different from national politics and centers
on groups and interests not ideology, especially in settings where local officeholders
are elected in nonpartisan elections. A newer literature casts doubt on this, finding a
connection between partisan voting, local ideology, and policy mimicking the federal
level and without reference to groups and interests. In this paper, I use a large original
data set on the professional backgrounds of city councilors to provide a link between
the evidence for both the old and new theories. I look at city council candidate emergence
and its policy consequences using two samples: 97 large American cities and
all 477 cities in California. After controlling for the share of city constituents in each
occupational category, liberal cities have more career politicians, non-profit workers,
and service based professionals running for and holding office, while conservative cities
have more military and law enforcement workers and business types running for and
holding office. Using voter files to look up candidates’ partisanship reveals partisan
trends across occupational categories. There is strong support for a theory of local
politics that accounts for the link between the economic backgrounds of politicians
and the information on partisanship that it signals.